In [11]:
import numpy as np

In [12]:
a = np.random.randn(1,5)
print(a)

[-0.35049163  0.27935582 -0.08835791 -0.74050182 -0.23391265]


In [13]:
print(a.shape)

(5,)


In [14]:
print(a.T)

[-0.35049163  0.27935582 -0.08835791 -0.74050182 -0.23391265]


In [15]:
print(np.dot(a,a.T))

0.8117492460461895


In [16]:
a = np.random.randn(5,1)
print(a)

[[ 0.98713989]
 [ 0.17589503]
 [-0.24315542]
 [ 0.75175291]
 [ 0.22602091]]


In [17]:
print(a.T)

[[ 0.98713989  0.17589503 -0.24315542  0.75175291  0.22602091]]


In [18]:
print(np.dot(a,a.T))

[[ 0.97444517  0.173633   -0.24002842  0.74208529  0.22311426]
 [ 0.173633    0.03093906 -0.04276983  0.1322296   0.03975595]
 [-0.24002842 -0.04276983  0.05912456 -0.18279279 -0.05495821]
 [ 0.74208529  0.1322296  -0.18279279  0.56513244  0.16991188]
 [ 0.22311426  0.03975595 -0.05495821  0.16991188  0.05108545]]
